### ISSUE TITLE
Contact page | Contact form is not working

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#1]
Contact form   >   Contact form is not working

**Comment by Priya-Quadrish** [comment]
![a](https://user-images.githubusercontent.com/51991326/60509156-e41e1300-9ce9-11e9-8469-aa320d951c25.jpg)

**Comment by Gaurav-Quadrish** [comment]
I have studied regarding mail issue. 
and try to fix it with the help of "Easy WP SMTP" WordPress plugin.

**Comment by Gaurav-Quadrish** [comment]
i have fixed sending mail issue. now its working.
![screencapture-quadrish-contact-2019-07-03-10_29_37](https://user-images.githubusercontent.com/52441095/60590186-fe72f200-9db8-11e9-9d1e-0877d3f20f3a.jpg)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
