### ISSUE TITLE
Mobile view  |  Header is overlapping

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#10]
When we open/close the navigation menu -Header is overlapping.
![10.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/6bb1268d-9243-4e54-9e0e-f2b5fbbc52e8)

**Comment by Gaurav-Quadrish** [comment]
i have fixed the Header overlapping issue.

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
