### ISSUE TITLE
Page: Portfolio | App Name

### ISSUE THREAD

**Issue by Sukhvir-Quadrish** [Quadrish/Quadrish-Website#102]
Please write the correct name of app, without any special symbol.

![image](https://user-images.githubusercontent.com/48615379/64848622-48851900-d62f-11e9-823d-cedf4c9c0d8f.png)

**Comment by Gaurav-Quadrish** [comment]
I removed the special symbol, please check.
![portfolio](https://user-images.githubusercontent.com/52441095/64937596-6a251100-d878-11e9-821c-690037aff67e.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
