### ISSUE TITLE
Blog page | Remove the extra heading and bar/ line from the banner

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#104]
Blog page | Remove the extra heading and bar/ line from the banner
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/4fd8697b-380e-41b5-9c45-acd9d2b2a781)

**Comment by Gaurav-Quadrish** [comment]
Removed the extra heading and bar/ line from the banner, please check it.
![post](https://user-images.githubusercontent.com/52441095/65041464-72fb0d00-d974-11e9-90eb-1a18cb85efbb.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
