### ISSUE TITLE
Blog page | Make the blog page responsive

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#105]
Blog page | Make the blog page responsive
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/242cfe36-a290-4d53-aede-9f575379136c)

**Comment by Gaurav-Quadrish** [comment]
Now blog page is responsive, please check,

**Comment by Priya-Quadrish** [comment]
Shift the read more button for the below screen size to left side and utilise the free space.
![image](https://user-images.githubusercontent.com/51991326/65304673-dbc5cd80-db9e-11e9-95f9-6680f04adfbe.png)

**Comment by Gaurav-Quadrish** [comment]
The design is changed according to you please assign me a new ticket for new design.

**Comment by Priya-Quadrish** [comment]
Done, Check ticket 113
