### ISSUE TITLE
Blog page | Post comment button

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#106]
Blog page | Post comment button - Make it similar with the submit button of contact form.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/4dda426a-bc39-4bbe-979e-3c5f1f4e9bb2)

**Comment by Gaurav-Quadrish** [comment]
Now  it is similar with the submit button of contact form.

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
