### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#107]
Change the "Contact us" Text to "Contact Us"
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/768d10d8-b4b3-4bdd-8168-81671b8732fd)

**Comment by Gaurav-Quadrish** [comment]
I changed text, please check

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
