### ISSUE TITLE
Mobile view  |  Positioning of header

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#11]
Header is not aligned at the top, on scrolling ; it is showing the background content moving.
![19.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/4d382725-ed0d-4d9b-a237-3fc63953afc3)

**Comment by Gaurav-Quadrish** [comment]
i fixed it please check the screenshots. ![image](https://user-images.githubusercontent.com/52441095/60971069-fd097280-a340-11e9-9cb0-831011f3ccfe.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
