### ISSUE TITLE
Homepage | Hero banner | Content positioning issue

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#111]
Hero banner - content is not in a container; hence content is cropping.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/ca9a80b1-01f3-43eb-aa10-29a60565ce35)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue and now content is not cropping. please check it.

**Comment by Priya-Quadrish** [comment]
This issue has been fixed, it is working fine now.
