### ISSUE TITLE
Header and banner image | Change the text

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#112]
Change the text ton "About US"
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/20a233d6-acfb-496f-8a12-03edf5e698fe)

**Comment by Gaurav-Quadrish** [comment]
I changed the text, please check,

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
