### ISSUE TITLE
Mobile view  |  Portfolio page  |  Text is not aligned vertically centered

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#12]
Text is not aligned vertically centered
![20.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/e1f063b5-1653-496b-a78f-02622789cfa8)

**Comment by Gaurav-Quadrish** [comment]
i fixed the title position ![image](https://user-images.githubusercontent.com/52441095/61023808-063e2200-a3c9-11e9-8241-81ce6d040112.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
