### ISSUE TITLE
Mobile view  |  Footer  | Contact's link

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#13]
Footer  >  contact (link is missing)
![21.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/98376437-9493-4940-a901-cff282eae9f1)

**Comment by Gaurav-Quadrish** [comment]
now link is working

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
