### ISSUE TITLE
Mobile view  |  Navigation menu

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#14]
Separate the navigation menus with thin grey line.
Also, show the active / inactive tabs.
![22.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/04a60c8c-2fad-4689-8d5d-352904195b1f)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue. please check the screenshot. 
![Screen Shot 2019-07-25 at 12 33 42](https://user-images.githubusercontent.com/52441095/61859742-57c8cf80-aee6-11e9-9c92-4f6896686d10.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
