### ISSUE TITLE
Mobile view  |  Privacy policy page 

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#15]
Privacy policy  >   Add some line height in the highlighted section.  Also, the section below it is blurry.
![23.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/9c2e9b7e-5cb3-4509-9b18-7937c583100c)

**Comment by Gaurav-Quadrish** [comment]
i Added some line height in the **accordion section**.

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is fixed now.
