### ISSUE TITLE
Mobile view  |  Navigation menu  |  Double header logo popup

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#17]
On closing and opening the navigation menu, double logo is popping out.
Check the below link.
https://www.screencast.com/t/qf2064MImTG

**Comment by Gaurav-Quadrish** [comment]
Now this issue has been fixed, please check it.

**Comment by Priya-Quadrish** [comment]
It is still pending.
check the below link.
https://www.screencast.com/t/gYjE1xIH

**Comment by Gaurav-Quadrish** [comment]
Its working from my side. 
![Screenshot_2019-07-03 Quadrish(1)](https://user-images.githubusercontent.com/52441095/60592177-b60a0300-9dbd-11e9-83eb-c60926f0165f.png)

**Comment by Priya-Quadrish** [comment]
Still the issue is pending, make sure to perform this task in all mobile screen sizes.

**Comment by Gaurav-Quadrish** [comment]
Now i fixed it for every media screen size.

**Comment by Priya-Quadrish** [comment]
This issue has been fixed, it is working fine now.
