### ISSUE TITLE
Client visit page

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#18]
Client's photos are missing in desktop and mobile view.
![2019-07-04_1006.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/ff6f9a1c-e544-48e7-94ce-63f161ca313c)

**Comment by Gaurav-Quadrish** [comment]
i have fixed the images issue, please check 
![Screen Shot 2019-07-03 at 10 16 42](https://user-images.githubusercontent.com/52441095/60648704-151f5480-9e5e-11e9-81eb-2b16c7bd4f9e.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
