### ISSUE TITLE
Page: All | View : All | Set the position of arrow icon 

### ISSUE THREAD

**Issue by Sukhvir-Quadrish** [Quadrish/Quadrish-Website#20]
Please make sure the icon of arrow should be in the center on white circle. You can the difference in below screenshot.

![Capture.PNG](https://images.zenhubusercontent.com/5c8caf06d74bd07972c7f03c/890ac512-a7a7-4291-80f3-79be4ee5d512)

**Comment by Gaurav-Quadrish** [comment]
i fixed the arrow position, please check now. ![image](https://user-images.githubusercontent.com/52441095/61348921-ed79b480-a87f-11e9-952b-693e8cc1217f.png)

**Comment by Sukhvir-Quadrish** [comment]
Above issue is working fine on live.

![image](https://user-images.githubusercontent.com/48615379/61350652-ef467680-a885-11e9-9086-5d6815c9c9b6.png)
