### ISSUE TITLE
Mobile view  |  Service page 

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#21]
Add the services :

-SOFTWARE DEVELOPMENT
-SERVER DEPLOYMENT
-SUPPORT AND MAINTENANCE
-CONSULTANCY SERVICES
with their links .
![1.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/1445b668-0c01-4170-94e9-76a08c9a24ec)

**Comment by Gaurav-Quadrish** [comment]
there are already 5 services mentioned in mobile view
![Screenshot_2019-07-03 Services – Quadrish](https://user-images.githubusercontent.com/52441095/60722463-a1a94000-9f4e-11e9-8c12-c6a5c979ae28.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
