### ISSUE TITLE
Mobile view  |  Story page-client's visit and events

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#22]
Remove the extra spacing from Story page-client's visit and events.
Check the below link.
https://www.screencast.com/t/PQn0H2yW0Z

**Comment by Gaurav-Quadrish** [comment]
i fixed the space issue ![image](https://user-images.githubusercontent.com/52441095/61029696-3c839d80-a3d9-11e9-82f2-2ca3a1dac842.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
