### ISSUE TITLE
Mobile view  |  Homepage |  Services section

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#23]
Under the services section in homepage ; avoid the extra spacing or make the highlighted spaces equal.
Check the below image.
![1.2.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/94112df7-a0b3-467b-9d36-1f1b04873b28)

**Comment by Gaurav-Quadrish** [comment]
i fixed this space for every media screens size 
![image](https://user-images.githubusercontent.com/52441095/60969321-e103d200-a33c-11e9-9264-9e4e500ba82e.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
