### ISSUE TITLE
Mobile  |  Landscape view |  Heading of hero banner

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#24]
Heading of hero banner is cropping .

![1.3.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/c5c8552f-488c-4e07-a7e9-902e93628fea)

**Comment by Gaurav-Quadrish** [comment]
its not cropping now, ![image](https://user-images.githubusercontent.com/52441095/60871336-28f8fb00-a250-11e9-852a-50b212a9e929.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
