### ISSUE TITLE
Mobile  |  Landscape view  | Portfolio page

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#25]
Portfolio's image display is not correct in landscape view. It is adding some unwanted structures with the portfolio image.
![1.4.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/08ea09c2-b155-42f8-b539-284f1af0a164)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue for every media screen sizes.  ![image](https://user-images.githubusercontent.com/52441095/61212717-b04ae080-a720-11e9-9588-5aa939a3bd5c.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
