### ISSUE TITLE
Mobile  |  Landscape view  | Homepage

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#26]
Homepage (landscape view )- under the services section ; the image is blurry .
Also, in this case ; shift the text to a little upward direction and increase its font size.

![1.5.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/cec70e30-b2ef-420e-aa1e-2989538c516b)

**Comment by Gaurav-Quadrish** [comment]
i resize the images and increased the font size, ![image](https://user-images.githubusercontent.com/52441095/60885031-26a49a00-a26c-11e9-9c6e-3513ad15c087.png)

**Comment by Priya-Quadrish** [comment]
The above issue is still pending.
Check the issue for home page.
![2 1](https://user-images.githubusercontent.com/51991326/60887095-265acd80-a271-11e9-87ac-0a251556024c.png)

**Comment by Gaurav-Quadrish** [comment]
i solve it for home page.  ![Screen Shot 2019-07-08 at 17 16 09](https://user-images.githubusercontent.com/52441095/60887532-4a6ade80-a272-11e9-9dae-f15133313ab0.png)

**Comment by Priya-Quadrish** [comment]
Use same width and height for all the images used in this particular section.

**Comment by Priya-Quadrish** [comment]
As; you had already made some changes for the homepage | service section's images(in other ticket ; made the width and height similar)
Hence, this issue has been fixed by itself.

This issue has been fixed , it is working fine now.
