### ISSUE TITLE
Mobile  |  Landscape view  |  Story - client's visit and events page

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#27]
Landscape view  |  Story - client's visit and events page  - Utilize the empty space by adding image on it.
Check the below image.

![1.6.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/65447bf1-a568-4f3a-a4d5-e6b517acfe69)

**Comment by Gaurav-Quadrish** [comment]
i shift the image please check ,, ![Screen Shot 2019-07-08 at 16 36 06](https://user-images.githubusercontent.com/52441095/60807826-512b2000-a1a4-11e9-8fee-dd155187b20a.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
