### ISSUE TITLE
Mobile view  |  Header's shadow

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#29]
Header's shadow is too dark, reduce the darkness of the shadow.
![3.1.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/43128415-4df8-49a6-b447-dd27f63c29f7)

**Comment by Priya-Quadrish** [comment]
Also , in navigation menu, header's shadow is very dark.

![3 4](https://user-images.githubusercontent.com/51991326/60965576-c547fe00-a333-11e9-9423-b2bdf5cdc3f6.png)

**Comment by Gaurav-Quadrish** [comment]
i reduced the shadow color ![image](https://user-images.githubusercontent.com/52441095/60970268-3d67f100-a33f-11e9-8d81-e6bc525397f5.png)

**Comment by Priya-Quadrish** [comment]
Match the mobile's header shadow with the header shadow of desktop view.

![4 2](https://user-images.githubusercontent.com/51991326/61045003-8da28a00-a3f7-11e9-99cc-10c54decd48a.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed it now. ![image](https://user-images.githubusercontent.com/52441095/61045363-5da7b680-a3f8-11e9-9220-cbdb8e6346e0.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
