### ISSUE TITLE
Services  |  Consultancy services

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#3]
I have opened the sub category(Consultancy services) of "Services " , it must highlight the main category on the header.
![3.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/50ba204c-e54f-402a-8726-a522e4fb5ac8)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue. please check the screenshot. 
![image](https://user-images.githubusercontent.com/52441095/61860150-1d136700-aee7-11e9-9e60-a6aec4c1f5b3.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested ,it is working fine now.
