### ISSUE TITLE
Desktop view |  Homepage  |  Service's image section

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#30]
Images are not of same width and height.
![3.3.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/da72f572-10b2-4425-9c72-dfe697e01b52)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue ![image](https://user-images.githubusercontent.com/52441095/60966692-6f288a00-a336-11e9-98cb-e26b49abc040.png)

**Comment by Priya-Quadrish** [comment]
This issue has been fixed , it is working fine now.
