### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#31]
Add google analytics for the quadrish website.

**Comment by Gaurav-Quadrish** [comment]
i added the google analytics please check the screenshot 
![image](https://user-images.githubusercontent.com/52441095/61865708-5224b700-aef1-11e9-91a3-44e21dbab9af.png)

**Comment by Priya-Quadrish** [comment]
This feature has been tested, it is working fine.
