### ISSUE TITLE
Footer  |  Font weight (contact text)

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#33]
Make the font weight of contact heading similar with the corresponding heading in the footer.![4.1.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/af4c7061-4c7e-4273-b98b-c54f544a4caf)

**Comment by Gaurav-Quadrish** [comment]
issue is fix now. ![image](https://user-images.githubusercontent.com/52441095/61046506-f17a8200-a3fa-11e9-8ba8-9e8f3bc0f5a9.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
