### ISSUE TITLE
Mobile  |  Navigation menu  |  Highlight the heading of the selected page.

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#4]
Mobile  >  Navigation menu  >  when I am in the home page, it must highlight the home menu.
![4.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/f71fe36d-e3b8-4481-b800-dff06e4b88a7)

**Comment by Gaurav-Quadrish** [comment]
now the page menu is highlight ,, please check the screenshot 
![Screenshot_2019-07-03 About – Quadrish](https://user-images.githubusercontent.com/52441095/60721629-35c5d800-9f4c-11e9-8628-5ae6182f607e.png)

**Comment by Priya-Quadrish** [comment]
Issue is still pending;
As it is not showing the category : active ; when the sub categories are opened.
Also, showing highlighted section in two different ways.
Check the below link for better understanding.

https://www.screencast.com/t/HTyROoQ444

**Comment by Gaurav-Quadrish** [comment]
now its working 
![Screen Shot 2019-07-25 at 12 23 10](https://user-images.githubusercontent.com/52441095/61864362-e9d4d600-aeee-11e9-9c24-9fbe00da8df9.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
