### ISSUE TITLE
Real mobile device  |  Footer overlaps the navigation menu

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#42]
Footer is overlapping the navigation menu.

**Comment by Gaurav-Quadrish** [comment]
i fixed the Footer overlapping issue. 
<img width="736" alt="Screenshot 2019-08-08 at 3 54 08 PM" src="https://user-images.githubusercontent.com/52441095/62695986-1e6b8600-b9f5-11e9-96d5-e367c2927f29.png">

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
