### ISSUE TITLE
Real mobile device |  Scroll arrow overlaps the navigation menu

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#43]
scrolling arrow is overlapping with the navigation menu.

**Comment by Gaurav-Quadrish** [comment]
I fixed the scrolling arrow overlapping issue, please check the screenshot.
<img width="387" alt="Screenshot 2019-08-08 at 3 53 44 PM" src="https://user-images.githubusercontent.com/52441095/62696093-54a90580-b9f5-11e9-975b-cd041c546f85.png">

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
