### ISSUE TITLE
Real mobile device  |  Landscape view  |  header is not fixed

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#45]
Header is not fixed throughout the page in the landscape view.

**Comment by Gaurav-Quadrish** [comment]
Now header is fixed in every Real mobile device.
![Untitled](https://user-images.githubusercontent.com/52441095/62698555-0991f100-b9fb-11e9-8bb7-17d8463d6a74.png)

**Comment by Priya-Quadrish** [comment]
This issue has been fixed, it is working fine now.
