### ISSUE TITLE
Footer  |  Make the footer responsive with all the screen sizes.

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#5]
Maintain the responsive of footer in all screen sizes.
Avoid side spacing and maintain equal spacing between the highlighted headings. 
Also, reduce the size of scroll up icon.
![5.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/07b0395d-d399-4c79-8de7-ff54753fc4ae)

**Comment by Gaurav-Quadrish** [comment]
i reduced the size and Avoid the extra space.
![Screenshot_2019-07-03 Quadrish](https://user-images.githubusercontent.com/52441095/60591704-a4742b80-9dbc-11e9-872d-1bdc0ab37166.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is fixed now.
