### ISSUE TITLE
Solutions page  |  

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#50]
Check the below image and fix the link image issue.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/a26ee6ee-4d25-44e6-a521-3544b9995734)

**Comment by Gaurav-Quadrish** [comment]
i fix this issue.
![solution-page](https://user-images.githubusercontent.com/52441095/62364142-6ba3af80-b53e-11e9-8002-e10fc32d3d7c.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
