### ISSUE TITLE
LinkedIn link

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#53]
Add the linkedIn link in the footer with the linkedIn logo.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/4c8aced7-e1c0-4670-91a3-b1ac270afe0b)

**Comment by Gaurav-Quadrish** [comment]
i added the social link in footer section.
![Screenshot_2019-07-31 Quadrish - Innovations Private Limited(4)](https://user-images.githubusercontent.com/52441095/62463817-9db84a00-b7a8-11e9-9bd7-ff8f9b612484.png)

**Comment by Priya-Quadrish** [comment]
Align the instagram icon on the specific location not at the copyright section.
![image](https://user-images.githubusercontent.com/51991326/62515036-b5daa880-b83e-11e9-9f0d-0a3451615d38.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue foe all media screen size.
![Untitled](https://user-images.githubusercontent.com/52441095/62524623-90a46500-b853-11e9-9aa8-c642c112e859.png)

**Comment by Priya-Quadrish** [comment]
Align the linkedin icon to the positions mentioned below. (for all different screen sizes - positioning of icon is shown below)

![image](https://user-images.githubusercontent.com/51991326/62595419-e7fe1000-b8fb-11e9-8586-c8c7b701280c.png)
![image](https://user-images.githubusercontent.com/51991326/62595453-1845ae80-b8fc-11e9-8306-f5e9bf595f5f.png)
![image](https://user-images.githubusercontent.com/51991326/62595511-40351200-b8fc-11e9-917b-4c8854fe1b42.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed the positions for different media screen sizes. 
![2](https://user-images.githubusercontent.com/52441095/62614791-b734cf80-b929-11e9-9622-2eedf14d05bc.png)
![3](https://user-images.githubusercontent.com/52441095/62614792-b7cd6600-b929-11e9-85ed-e047f3ef8ae8.png)
![Untitled](https://user-images.githubusercontent.com/52441095/62614796-b865fc80-b929-11e9-8729-ac1d1b16689f.png)

**Comment by Priya-Quadrish** [comment]
Align footer :
1 column - about , services , contact
2 column - Skype id , mail id
3 column - linkedin account
![image](https://user-images.githubusercontent.com/51991326/62686962-671a4380-b9e3-11e9-9893-aa7d1b2f8e40.png)

**Comment by Priya-Quadrish** [comment]
Add a white/grey thin line to separate the sections in footer, as shown in the image below.
Also, shift the content little towards side hand side.

![image](https://user-images.githubusercontent.com/51991326/62916002-386de580-bdb4-11e9-830d-6d52ca3bc81d.png)

**Comment by Gaurav-Quadrish** [comment]
I added right border and also shifted the content right hand side.
![Untitled](https://user-images.githubusercontent.com/52441095/62927675-a7f3cd00-bdd4-11e9-8429-c657b67daeb5.png)

**Comment by Priya-Quadrish** [comment]
Shift the content to RHS.(so that the 3 columns will get equal spacing)
![image](https://user-images.githubusercontent.com/51991326/62995774-c367e200-be7f-11e9-8502-deb7d06fefbf.png)

**Comment by Gaurav-Quadrish** [comment]
Fixed the footer section and removed the extra space. 
![Untitled](https://user-images.githubusercontent.com/52441095/63146426-86832300-c018-11e9-9f29-5919bd4f0af0.png)

**Comment by Priya-Quadrish** [comment]
place the icon on the right positions according to the different screen sizes.
![image](https://user-images.githubusercontent.com/51991326/63427777-93967c80-c433-11e9-93d7-591b935eed6b.png)

**Comment by Priya-Quadrish** [comment]
Also utilize the space to display the  footer properly in small screens.
![image](https://user-images.githubusercontent.com/51991326/63427941-eff99c00-c433-11e9-93f8-78210ce30536.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue.
![footer](https://user-images.githubusercontent.com/52441095/64342021-43104900-d007-11e9-9c5e-dfc3bd106d56.png)

**Comment by Priya-Quadrish** [comment]
I have tested the issue, it is working fine now.
