### ISSUE TITLE
Header  |  Sub categories

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#59]
Unbold/remove the weightage from the sub categories on the header.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/2596ee5f-3c28-430a-b57e-e54219eb16ad)

**Comment by Gaurav-Quadrish** [comment]
i fixed the sub menu font issue. 
![client-visit-page](https://user-images.githubusercontent.com/52441095/62460476-b8d28c00-b79f-11e9-819c-9d844a0f4458.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
