### ISSUE TITLE
Header logo overlapping

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#60]
Header logo and category's name is overlapping
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/0f112ddd-8262-4b64-b910-ff52c35f4192)

**Comment by Gaurav-Quadrish** [comment]
i fixed Header logo overlapping issue.
![Screenshot_2019-07-31 Quadrish - Innovations Private Limited](https://user-images.githubusercontent.com/52441095/62455636-75265500-b794-11e9-9611-be24624c6e68.jpg)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
