### ISSUE TITLE
Navigation menu is not displaying properly.

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#61]
Navigation menu issue
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/42a62551-e07d-4d11-b1dc-fb68577d77c4)

**Comment by Gaurav-Quadrish** [comment]
i fixed sub-menu issue. 
![sub-menu](https://user-images.githubusercontent.com/52441095/62459557-5082ab00-b79d-11e9-942e-eaf61392c9c1.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
