### ISSUE TITLE
Hero banner text is not vertically center aligned.

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#62]
Hero banner text issue.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/946c08a8-1d93-4c04-93f6-f0284e8b7d4c)

**Comment by Priya-Quadrish** [comment]
![image](https://user-images.githubusercontent.com/51991326/62447139-43a48e00-b782-11e9-9b64-5bff99409dfc.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed the banner issue. 
![Untitled](https://user-images.githubusercontent.com/52441095/62459413-e964f680-b79c-11e9-9f0e-cb53a87fa80b.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
