### ISSUE TITLE
Services  |  Sub pages - image size issue.

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#64]
Maintain the image size and resolution for all the responsive screen.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/a201ed94-418b-4efa-8238-37431a63d8d3)

**Comment by Gaurav-Quadrish** [comment]
i fixed the image issue. 
![Screenshot_2019-07-31 Quadrish - Innovations Private Limited(1)](https://user-images.githubusercontent.com/52441095/62449741-781b4880-b788-11e9-9ed6-5ed5bb6af132.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested , it is working fine now.
