### ISSUE TITLE
Mobile view  | Portfolio page  |  Avoid extra spacing and align both button together.

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#8]
Avoid the space wastage , also show the apps and web button together, like it is in desktop.
![9.jpg](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/66438631-cf8c-444e-9786-ed6f04f3f6a1)

**Comment by Gaurav-Quadrish** [comment]
i fixed this issue.  ![Screenshot_2019-07-15 Portfolio - Quadrish](https://user-images.githubusercontent.com/52441095/61266831-3adc2000-a7b3-11e9-9c9f-b9a88346d180.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested,it is fixed now.
