### ISSUE TITLE
Navigation menu - Overlapping issue

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#83]
Highlighted - Navigation menu is overlapping.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/1349b8cf-41bd-471c-9d45-082418539283)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue.
![menu-panel](https://user-images.githubusercontent.com/52441095/63769000-4c0a6780-c8ef-11e9-9439-28a5189c2b6f.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
