### ISSUE TITLE
Unwanted icon in the footer

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#84]
Remove the unwanted icon from the footer, shown in the image below.

![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/0a5b75b1-5026-42bf-a1d1-9d1446bf88fc)

**Comment by Gaurav-Quadrish** [comment]
i removed unwanted icon.
![unwanted-icon](https://user-images.githubusercontent.com/52441095/63690308-e6a07300-c829-11e9-8e87-8fe4ccc7d4c3.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
