### ISSUE TITLE
Change the font to uppercase

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#85]
Change the U-letter of "About us" into upper case.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/d0c43d73-a3c7-4ec7-b708-5fab03d002e2)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue..
![footer](https://user-images.githubusercontent.com/52441095/63689907-db991300-c828-11e9-8a60-882249639cea.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
