### ISSUE TITLE
Text of hero banner slider

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#86]
Make changes to the text of hero banner slider, as shown in image below.
image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/dc8bdf5f-5d54-4bf6-af8e-943536b7eb1b)

**Comment by Gaurav-Quadrish** [comment]
i fixed the position of text please check it.

**Comment by Priya-Quadrish** [comment]
Make the text centrally aligned, also read more button is not at the center.
Make sure to make the changes for all the responsive screens.
![image](https://user-images.githubusercontent.com/51991326/64592941-baa8f400-d3ca-11e9-92ae-f4bcedace129.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed the text position for all views. please check .

**Comment by Priya-Quadrish** [comment]
Still the issue is pending, please check all responsive screens.
![image](https://user-images.githubusercontent.com/51991326/65222702-3eef2b80-dadd-11e9-8ce3-7fdaaf07fc52.png)
![image](https://user-images.githubusercontent.com/51991326/65222735-54645580-dadd-11e9-9e72-5c9726e5ce10.png)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue and content is responsive now, please check it.

**Comment by Priya-Quadrish** [comment]
This issue has been fixed, it is working fine now.
