### ISSUE TITLE
Inner pages banner issue

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#87]
*** hero banner slider should not effect the inner pages banner length and content.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/64da38ae-32ef-4779-bd06-2643f4af49cf)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue. 
![title-box](https://user-images.githubusercontent.com/52441095/63689619-1189c780-c828-11e9-829a-482b529735ae.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
