### ISSUE TITLE
Mobile view  |  Story page  |  Make the page responsive

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#9]
Make the stories  page responsive with small screens too.
![2019-07-02_1728.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/b9e0849c-80ba-4f8a-9cdd-7222c4ecfe2f)

**Comment by Gaurav-Quadrish** [comment]
i fixed the responsive issue please check, 
![Screen Shot 2019-07-03 at 10 56 58](https://user-images.githubusercontent.com/52441095/60651460-dee4d380-9e63-11e9-8925-d8058f8e40ed.png)

**Comment by Priya-Quadrish** [comment]
Events : add some space in between the images.
![4](https://user-images.githubusercontent.com/51991326/60667329-e8336780-9e86-11e9-84fe-daff9f4b1412.png)
Client visit : show two images in a row
![5](https://user-images.githubusercontent.com/51991326/60667389-0ac58080-9e87-11e9-8c9c-0ba9cae86a01.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed the responsive and space issue , 
![Screen Shot 2019-07-03 at 10 03 50](https://user-images.githubusercontent.com/52441095/60722308-29db1580-9f4e-11e9-87df-357a4af00b3f.png)
![Screenshot_2019-07-03 Events – Quadrish](https://user-images.githubusercontent.com/52441095/60722310-2a73ac00-9f4e-11e9-9012-c9446c592252.png)

**Comment by Priya-Quadrish** [comment]
Remove the extra space.
![a](https://user-images.githubusercontent.com/51991326/60722510-c3a2c280-9f4e-11e9-90bc-d6f187f1f22e.png)
![b](https://user-images.githubusercontent.com/51991326/60722512-c3a2c280-9f4e-11e9-97eb-a8a7807f020c.png)

**Comment by Gaurav-Quadrish** [comment]
i fixed the space issue. 
![Screenshot_2019-07-08 Events – Quadrish](https://user-images.githubusercontent.com/52441095/60807671-e679e480-a1a3-11e9-9794-edb965cd903b.jpg)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
