### ISSUE TITLE
Portfolio page 

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#90]
Content is overlapping.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/32ef5734-1b1e-4039-bb3f-176a94326ee7)

**Comment by Gaurav-Quadrish** [comment]
I fixed this issue. for every media screen size.

**Comment by Priya-Quadrish** [comment]
Check the overlapping issue for the screen shared below.
![image](https://user-images.githubusercontent.com/51991326/64314521-ded09380-cfcc-11e9-9d3f-5a2ccabd759d.png)

**Comment by Gaurav-Quadrish** [comment]
05-09-2019
*Fixed the position of **App** and **Web** buttons on portfolio page, for minimum width **320px to 800px** 
![portfolio](https://user-images.githubusercontent.com/52441095/64341104-499dc100-d005-11e9-8b7f-15a3409183a8.png)

*Also removed unnecessary css form app.css and titlebox > style2.css regarding these buttons. 

**Note:-** i will continue on this work by tomorrow for next remaining widths. (upto 800px)

**Comment by Gaurav-Quadrish** [comment]
06-09-2019
*Fixed the position of **App** and **Web buttons** on portfolio page, for every media screen sizes.

**Comment by Priya-Quadrish** [comment]
Web and app buttons are still overlapping.

![image](https://user-images.githubusercontent.com/51991326/64504782-f5d5f500-d2ee-11e9-9b0f-39fb9dc7ae2d.png)

**Comment by Gaurav-Quadrish** [comment]
09-09-2019
*Fixed the portfolio button position according to chrome browser.
i will continue it by tomorrow.

**Comment by Gaurav-Quadrish** [comment]
I fixed button issue, please check it.

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
