### ISSUE TITLE
Linkedin icon for desktop screens

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#94]
Instead of bottom as 50 px, change it to 30px.
So that the linkedin icon in the desktop will not appear just below the mail link but  with some distance in between them.
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/5a9eda63-6ac2-437d-b92c-defd25db2cf2)

**Comment by Gaurav-Quadrish** [comment]
i fixed it. 
![icon](https://user-images.githubusercontent.com/52441095/64426660-cba4ed00-d0cc-11e9-971a-5e738f1628d0.png)

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
