### ISSUE TITLE
Portfolio page | App /web - Button size

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#97]
Web and app button size is not similar.

![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/b941a157-f22f-40be-87b6-1a7c7de63c79)

**Comment by Gaurav-Quadrish** [comment]
The size of buttons is not showing equal, **because of the text (APPS and WEB) of the buttons are not in same size,** even the **id** and **classes** of both buttons are same, and also **css** are also **same** of both buttons.

**Comment by Priya-Quadrish** [comment]
okay.
