### ISSUE TITLE
Homepage | hero banner | Read more button is hiding

### ISSUE THREAD

**Issue by Priya-Quadrish** [Quadrish/Quadrish-Website#99]
Homepage | hero banner | Read more button is hiding
![image.png](https://images.zenhubusercontent.com/5d0a0eedd8501ed6b9d8600c/ad656747-6d90-486b-896b-da67f30fd9f6)

**Comment by Gaurav-Quadrish** [comment]
I fixed the button issue, please check,

**Comment by Priya-Quadrish** [comment]
This issue has been tested, it is working fine now.
